name: Build Artifact

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - run: cargo test --verbose
  build:
    needs: test
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      
      - run: cargo build --release --verbose
      - run: ls target/${{ matrix.target }}/release
      - name: Upload Bin
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ matrix.target }}_bin
          path: |
            target/${{ matrix.target }}/release/cczu-ical-rs
            target/${{ matrix.target }}/release/*.exe
      - name: Upload CDylib
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ matrix.target }}_cdylib
          path: |
            target/${{ matrix.target }}/release/*.dll
            target/${{ matrix.target }}/release/*.so
            target/${{ matrix.target }}/release/*.dylib